# Generated by Django 4.0.5 on 2022-06-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinOfDevice',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Devices.device')),
                ('pin_number', models.IntegerField(default=10)),
                ('pin', models.TextField(blank=True)),
            ],
        ),
    ]
