# Generated by Django 4.0.5 on 2022-07-10 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('versions', models.IntegerField(blank=True, default=1)),
                ('release', models.FileField(blank=True, upload_to='release/')),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auth.authdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_name', models.CharField(max_length=50, unique=True)),
                ('pin_number', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='PinOfDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, unique=True, serialize=False, to='Devices.device')),
                ('pin_number', models.IntegerField(default=10, editable=False)),
                ('pin', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('types', models.CharField(choices=[('INT', 'integer'), ('STR', 'string')], default=1, max_length=4)),
                ('validation', models.JSONField()),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Devices.sensor')),
            ],
            options={
                'unique_together': {('sensor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SensorForDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enable', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sensor', to='Devices.device')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.sensor')),
            ],
            options={
                'unique_together': {('device', 'id')},
            },
        ),
    ]
