# Generated by Django 4.0.5 on 2022-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_pinofdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinofdevice',
            name='pin',
            field=models.JSONField(blank=True),
        ),
    ]
