# Generated by Django 4.0.5 on 2022-07-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0003_relay_remove_sensorvaluetype_validation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_type', models.CharField(choices=[('NUM', 'number'), ('STR', 'string')], default=1, max_length=4)),
                ('operaror_name', models.CharField(choices=[('eq', 'equal'), ('gt', 'greater'), ('lt', 'lower'), ('ne', 'difference'), ('ge', 'greater and equal'), ('le', 'lower and equal')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensordevicevalidation',
            name='validation',
        ),
        migrations.AddField(
            model_name='sensordevicevalidation',
            name='active',
            field=models.IntegerField(choices=[(0, 'enable'), (1, 'disable')], default=0),
        ),
        migrations.AddField(
            model_name='sensordevicevalidation',
            name='operator_value',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordevicevalidation',
            name='relay',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Devices.relayfordevice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorvaluetype',
            name='types',
            field=models.CharField(choices=[('Num', 'Number'), ('STR', 'string')], default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='sensordevicevalidation',
            name='operator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Devices.operators'),
            preserve_default=False,
        ),
    ]
