# Generated by Django 4.0.5 on 2022-06-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0003_alter_pinofdevice_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinofdevice',
            name='pin_number',
            field=models.IntegerField(default=10, editable=False),
        ),
    ]
