# Generated by Django 4.0.5 on 2022-06-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_authdevice_id_authdevice_mac_addres_and_more'),
        ('Devices', '0004_alter_pinofdevice_pin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auth',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.authdevice'),
            preserve_default=False,
        ),
    ]
