# Generated by Django 4.0.5 on 2022-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0004_operators_remove_sensordevicevalidation_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordevicevalidation',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
