# Generated by Django 4.0.5 on 2022-07-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0005_device_auth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensorfordevice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sensorfordevice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='sensorfordevice',
            unique_together={('device', 'id')},
        ),
        migrations.RemoveField(
            model_name='sensorfordevice',
            name='value',
        ),
    ]
