# Generated by Django 4.0.5 on 2022-07-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0005_sensordevicevalidation_sort'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operators',
            unique_together={('operator_type', 'operaror_name')},
        ),
    ]
