# Generated by Django 4.0.5 on 2022-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0007_sensor_pin_number_sensorvaluetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorfordevice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
