# Generated by Django 4.0.5 on 2022-07-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0008_alter_sensorfordevice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorfordevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sensor', to='Devices.device'),
        ),
    ]
