# Generated by Django 4.0.5 on 2022-07-27 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0009_alter_timeaction_crontab'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('versions', models.IntegerField(blank=True, default=1)),
                ('release', models.FileField(blank=True, upload_to='release/')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='deviceModel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='Devices.devicemodels'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name', 'deviceModel')},
        ),
        migrations.RemoveField(
            model_name='device',
            name='release',
        ),
        migrations.RemoveField(
            model_name='device',
            name='versions',
        ),
    ]
