# Generated by Django 4.0.5 on 2022-07-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0010_devicemodels_alter_device_name_device_devicemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='release',
            field=models.FileField(blank=True, upload_to='media/release/'),
        ),
    ]
