# Generated by Django 4.0.5 on 2022-07-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0011_alter_devicemodels_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='release',
            field=models.FileField(blank=True, upload_to='release/'),
        ),
    ]
