# Generated by Django 4.0.5 on 2022-07-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('Devices', '0012_alter_devicemodels_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeaction',
            name='crontab',
        ),
        migrations.AddField(
            model_name='timeaction',
            name='PeriodicTask',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
            preserve_default=False,
        ),
    ]
