# Generated by Django 4.0.5 on 2022-07-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0013_remove_timeaction_crontab_timeaction_periodictask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeenable',
            name='sensorfordevice',
        ),
        migrations.DeleteModel(
            name='TimeAction',
        ),
        migrations.DeleteModel(
            name='TimeEnable',
        ),
    ]
