# Generated by Django 4.0.5 on 2022-08-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0014_remove_timeenable_sensorfordevice_delete_timeaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordevicevalidation',
            name='active',
            field=models.IntegerField(choices=[(1, 'enable'), (0, 'disable')], default=0),
        ),
    ]
