# Generated by Django 4.0.5 on 2022-08-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0015_alter_sensordevicevalidation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorfordevice',
            name='sampleDuration',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
