# Generated by Django 4.0.5 on 2022-06-23 18:48

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authdevice',
            name='id',
        ),
        migrations.AddField(
            model_name='authdevice',
            name='mac_addres',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authdevice',
            name='token',
            field=models.IntegerField(default=Auth.models.create_new_ref_number, primary_key=True, serialize=False, unique=True),
        ),
    ]
